### ISSUE TITLE
Endlessly loops on IE5 on Mac OS9

### ISSUE THREAD

**Issue by AbsolutelyLudicrous** [ttalvitie/browservice#32] opened 2021-03-31 17:55 UTC
Hello there!

When I try to use the Browservice proxy on classic Mac OS's IE, it endlessly loops between two(?) URLs. http://$IP/$Window#/$hash leads to http://$IP/$Window#/$hash/next, which leads back to http://$IP/$Window#/$hash. This occurs in both the version of IE5.0 bundled with OS9 and IE5.1.

**Comment by brunocastello** [comment] 2021-04-01 21:09
Have you tried the Netscape?

**Comment by ttalvitie** [comment] 2021-04-02 09:49
Good to hear experiences from the Mac OS side. I have no direct way to debug this myself, but the best theory about the cause that comes to mind is that for some reason, IE5 on Mac OS incorrectly caches the main page (http://$IP/$Window#/$hash) even though Browservice sends headers that disallow caching. Caching breaks things because the native Back/Forward button forwarding is implemented as a forwarding chain /prev/ -> / -> /next/ -> / on the first load of the Browservice client page (where the last forward is done by simulating a Back button press), and if IE5 uses the old cached version of /, we get a forward loop.

To confirm this theory, we need to log all the HTTP requests that Browservice receives. Could you try to add the line
```
    INFO_LOG("HTTP ", request->method(), " ", request->path());
```
to the beginning of the function `Context::onHTTPServerRequest` in [viceplugins/retrojsvice/src/context.cpp](https://github.com/ttalvitie/browservice/blob/v0.9.2.0/viceplugins/retrojsvice/src/context.cpp#L570). To apply the change, you can simply re-run the `make` command and restart Browservice. After this, connecting with IE5 to the modified Browservice instance, see what `HTTP GET` lines there are in the command line output. If it was running correctly, the output should look something like
```
topi@laptopi:~/vcs/browservice$ release/bin/browservice 2>&1 | grep HTTP
INFO @ retrojsvice.so src/http.cpp:620 -- Starting HTTP server (listen address: 127.0.0.1:8080)
INFO @ retrojsvice.so src/http.cpp:628 -- HTTP server started successfully
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/prev/
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/next/
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/image/1/1/1/1500/886/0/
INFO @ retrojsvice.so src/context.cpp:570 -- HTTP GET /1/XirNMFay3yQAXbdv2amTv8tNoKpLoEss/image/1/2/0/1500/886/0/
<Continues with lots of image requests>
```
However, if my theory is correct, you only get the first four `HTTP GET` requests, after which IE5 uses the cached pages.

An easy way to get around this bug is to disable the native Forward button forwarding by changing the initial value of `preMainVisited_` from `false` to `true` on line 63 in [viceplugins/retrojsvice/src/window.cpp](https://github.com/ttalvitie/browservice/blob/v0.9.2.0/viceplugins/retrojsvice/src/window.cpp#L63).

**Comment by brunocastello** [comment] 2021-04-18 18:33
This solution works.

**Comment by ttalvitie** [comment] 2021-04-25 12:51
I have formulated a more robust fix for this issue in the [disable-mac-ie-native-navigation](https://github.com/ttalvitie/browservice/tree/disable-mac-ie-native-navigation) branch. The fix selectively disables the native Back/Forward emulation when running IE on Mac. Could you try to run it and see if it still works?

**Comment by brunocastello** [comment] 2021-04-25 19:42
Sure. In a few days I can report back.

**Comment by brunocastello** [comment] 2021-05-01 19:41
Tried it, does not work at all. Browservice does not show up on IE 5.1.7 and the toolbar buttons keep blinking as if they were in an endless loop. 

The simple fix by changing the initial value of _preMainVisited_ still works with previous build, although the forward/stop buttons are still blinking while loading, but Browservice was working. I am reverting back to the clean master branch to apply the Classilla fix so I can continue using it on both browsers.

**Comment by ttalvitie** [comment] 2021-05-01 20:48
This is odd, as this should still essentially be the same fix than the one that worked before. Thus we should make sure that no manual changes are interfering. I made a new branch disable-mac-ie-native-navigation-debug that is based directly on v0.9.2.0, incorporates only the fix proposal for IE5 and adds some debug output for investigation in case it does not work. Please run the following in the `browservice-testing` working copy initialized in [this comment](https://github.com/ttalvitie/browservice/issues/33#issuecomment-830690306); make sure that there are no manual modifications in the working copy.

```
git fetch
git checkout disable-mac-ie-native-navigation-debug

# Recompile only the changed files
make -j5 debug

# Run Browservice; add command line options if necessary
debug/bin/browservice
```

If the fix does not work, paste the DEBUG lines in the output. One way to get all of them is by running Browservice as follows:
```
debug/bin/browservice 2>&1 | grep DEBUG
```

**Comment by ttalvitie** [comment] 2022-01-03 14:56
Closing due to lack of activity; please create a new issue if you still have this problem.

**Closed by ttalvitie** 2022-01-03 14:56 UTC
